#!/bin/zsh
# remember to push this BEFORE you run it!!
cat <<EOF | ssh yagni -T
  mkdir -p $HOME/painkiller
  git clone https://github.com/cruftbusters/painkiller-hillshade painkiller/hillshade
  cd painkiller/hillshade
  ln -s $HOME/painkiller/hillshade/scripts/painkiller.hillshade.service $HOME/.config/systemd/user/
  systemctl enable painkiller.hillshade --user
EOF
